Mappings: 
  AmiRegionMap: 
    us-east-1: 
      AMI: "ami-0277155c3f0ab2930"
    us-east-2: 
      AMI: "ami-0866a04d72a1f5479"
    us-west-1: 
      AMI: "ami-015e832ac6a60f0de"
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, from, cloudformation]]
      SecurityGroups:
        - !Ref VprofileSG

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from anywhere
      #VpcId: !Ref myVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0